version: '2'
services:
  web:
    build: ./src/ToDoApi
    ports:
      - "5000:5000"
    environment:
      - RabbitMQ__Uri=amqp://guest:guest@futurestack_rabbit_1:5672/%2f
      - RabbitMQ__Exchange=future.stack.exchange
      - Database__ToDo=ToDoDb.sqlite
      - Database__MessageStore=messages.sqlite
      - Database__MessageTableName=Messages
    links:
      - rabbit:todo_broker
  reverse_proxy:
    image: nginx
    ports:
      - "8080:80"
    depends_on:
      - web
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
  worker:
    build: ./src/ToDoApp
    environment:
      - RabbitMQ__Uri=amqp://guest:guest@futurestack_rabbit_1:5672/%2f
      - RabbitMQ__Exchange=future.stack.exchange
      - Database__ToDo=ToDoDb.sqlite
    links:
      - rabbit:todo_broker
  rabbit:
    hostname: todo_broker
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  
      - "15672:15672"  