version: '3.1'
services:
  web:
    build: ./ToDoBackend/src/ToDoApi
    hostname: todoweb
    ports:
      - "5000:5000"
    environment:
      - Database__ToDo=Server=todo_db;Uid=root;Pwd=root;Database=ToDoBackend
      - Database__ToDoDb=Server=todo_db;Uid=root;Pwd=root
    links:
      - mysql:todo_db
    depends_on:
      - mysql
  mysql:
    hostname: todo_db
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      test: mysqladmin ping -h localhost -p$$MYSQL_ROOT_PASSWORD && test '0' -eq $$(ps aux | awk '{print $$11}' | grep -c -e '^mysql$$')
    
