version: '2'
services:
  web:
    build: ./ToDoBackend/src/ToDoApi
    hostname: todoweb
    ports:
      - "5000:5000"
    environment:
      - RabbitMQ__Uri=amqp://guest:guest@todo_broker:5672
      - RabbitMQ__Exchange=future.stack.exchange
      - Database__ToDo=Server=todo_db;Uid=root;Pwd=root;Database=ToDoBackend
      - Database__MessageStore=Server=todo_db;Uid=root;Pwd=root;Database=ToDoBackend
      - Database__MessageTableName=Messages
    links:
      - rabbit:todo_broker
      - mysql:todo_db
    depends_on:
      - rabbit
      - mysql
  reverse_proxy:
    image: nginx
    ports:
      - "8080:80"
    links:
      - web:todoweb
    depends_on:
      - web
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
  worker:
    build: ./ToDoBackend/src/ToDoApp
    environment:
      - RabbitMQ__Uri=amqp://guest:guest@todo_broker:5672
      - RabbitMQ__Exchange=future.stack.exchange
      - Database__ToDo=Server=todo_db;Uid=root;Pwd=root;Database=ToDoBackend
    links:
      - rabbit:todo_broker
      - mysql:todo_db
    depends_on:
      - rabbit
      - mysql
  rabbit:
    image: rabbitmq:3-management
    hostname: todo_broker
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
  mysql:
    hostname: todo_db
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
