version: '2.1'
services:
  web:
    build: ./ToDoBackend/src/ToDoApi
    hostname: todoweb
    ports:
      - "5000:5000"
    environment:
      - RabbitMQ__Uri=amqp://guest:guest@todo_broker:5672
      - RabbitMQ__Exchange=future.stack.exchange
      - Database__ToDo=Server=todo_db;Uid=root;Pwd=root;Database=ToDoBackend
      - Database__MessageStore=Server=todo_db;Uid=root;Pwd=root;Database=ToDoBackend
      - Database__MessageTableName=Messages
      - Database__ToDoDb=Server=todo_db;Uid=root;Pwd=root
    links:
      - rabbit:todo_broker
      - mysql:todo_db
    depends_on:
      - rabbit
      - mysql
  workergitter:
    build: ./ToDoGitter/ToDoGitterApp
    environment:
      - RabbitMQ__Uri=amqp://guest:guest@todo_broker:5672
      - RabbitMQ__Exchange=future.stack.exchange
    links:
      - rabbit:todo_broker
    depends_on:
      - rabbit
      - web
  rabbit:
    image: rabbitmq:3-management
    hostname: todo_broker
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - "15672:15672"
      - "5672:5672"
  mysql:
    hostname: todo_db
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      test: mysqladmin ping -h localhost -p$$MYSQL_ROOT_PASSWORD && test '0' -eq $$(ps aux | awk '{print $$11}' | grep -c -e '^mysql$$')
      