version: '2'
services:
  web:
    build: ./src/ToDoApi
    ports:
      - "5000:5000"
    environment:
      - RabbitMQ__Uri=amqp://guest:guest@192.168.99.100:5672/%2f
      - RabbitMQ__Exchange=future.stack.exchange
      - Database__ToDo=ToDoDb.sqlite
      - Database__MessageStore=messages.sqlite
      - Database__MessageTableName=Messages
    links:
      - rabbit:todo_broker
  worker:
    build: ./src/ToDoApp
    environment:
      - RabbitMQ__Uri=amqp://guest:guest@192.168.99.100:5672/%2f
      - RabbitMQ__Exchange=future.stack.exchange
      - Database__ToDo=ToDoDb.sqlite
    links:
      - rabbit:todo_broker
  rabbit:
    hostname: todo_broker
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  
      - "15672:15672"  