version: '2'
services:
  web:
    build: ./src/ToDoApi
    ports:
      - "5000:5000"
    environment:
      - RabbitMQ__Uri=amqp://guest:guest@rabbit:5672/%2f
      - RabbitMQ__Exchange=future.stack.exchange
      - Database__ToDo=ToDoDb.sqlite
      - Database__MessageStore=messages.sqlite
      - Database__MessageTableName=Messages
    links:
      - rabbit
    depends_on:
      - rabbit
  worker:
    build: ./src/ToDoApp
    environment:
      - RabbitMQ__Uri=amqp://guest:guest@rabbit:5672/%2f
      - RabbitMQ__Exchange=future.stack.exchange
      - Database__ToDo=ToDoDb.sqlite
    links:
      - rabbit
    depends_on:
      - rabbit
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.6.0
    ports:
      - "5672:5672"  
      - "15672:15672"  