version: '2.1'

services:
  calendar-db:
    container_name: calendar-db
    build: ./db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=docker
    ports:
      - "5432:5432"
    healthcheck:
      test: exit 0

  calendar-web:
    container_name: calendar-web
    build: ./
    command: ./EntryPoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000" # expose ports HOST:CONTAINER
    environment:
      - FLASK_CONFIG=development
      - DEV_DATABASE_URL=postgres://docker:password@calendar-db:5432/calendar_dev
      - TEST_DATABASE_URL=postgres://docker:password@calendar-db:5432/calendar_test
    depends_on:
      calendar-db:
         condition: service_healthy
    links:
      - calendar-db


